#!/usr/bin/perl 
# by JP Mens

use strict; 
my $zonefile = '/var/named/master/bzl-zonefile.db';
my $serial   = time; 
my $mname    = 'localhost.';              # Primary
my $rname    = 'jpmens.no.where.';        # Responsible
my $now      = localtime;
my $BZL      = './bzl';                   # path to `bzl'
my $bindURL  = 'http://127.0.0.1:8053/';  # BIND XML stats URL

my ($nzones); 

open ZONEF, "> $zonefile"  or
        die "Can't creat $zonefile: $!\n"; 

print ZONEF <<EndSOA; 
\$TTL 1H 
;  generated by $0 (bzl) on $now
;
;
@  IN SOA  $mname $rname $serial 1H 1H 1W 60   
@  IN NS   localhost.
EndSOA

open ZONELIST, "$BZL $bindURL 2>&1|"  or die "Can't get bzl: $!\n"; 
while (<ZONELIST>) { 
    chomp; 
    my ($ser, $zone, $class, $view) = split(/\s+/, $_, 4); 

    next if ($class eq 'CH');
    next if (!$ser);    # Skip internal zones with SOA serial 0

    printf ZONEF "%-40s IN TXT \"%s\"\n",    $zone, $ser;
    ++$nzones; 
} 
close ZONELIST; 

printf ZONEF "\n%-40s IN TXT \"%d\"\n", "bzl-nzones", $nzones;
close ZONEF; 
#--ends
